#!/usr/bin/python

from fbchat import Client
from fbchat.models import *
import fbchat

#cli object used to log-in password is stored in file
file1 = open("C:\\Users\\John\\Desktop\\PASSWORD_FILE", "r")
password = file1.read()
cli = Client('FACEBOOK LOGIN', password)

#searches for people on Facebook and displays x amount of results
person = str(input("Enter the person's name"))
numresults = input("How many search results would you like?")
friends = cli.searchForUsers(person, numresults)
print ("Everyone named " + str(person) + ":")
for people in friends:
    print (people)

# a For loop that will send a friend request to everyone in your search results. 
# for i in friends:
#     print (i.uid)
#     fconnect = i.uid
#     fbchat.Client(fconnect), friendconnect

#Identifies the first search result and stores User ID
user1 = friends[0]
uiid = user1.uid

#Prints UserID, Name and Boolean T or F if they are a friend
print(user1.name)
print(user1.uid)
print("Is this user my friend? " + str(user1.is_friend))

# Displays last 5 messages between you and user1
messages = cli.fetchThreadMessages(user1.uid, 5)
messages.reverse()
for msg in messages:
    print (msg)

#Sends the person a message
# cli.send(fbchat.models.Message("Hi " + str(person) + " This message was sent by a bot that I made"), uiid)

#Logs you out and confirms that you logged out
res = cli.logout()
if res:
    print("Logged out success")
else:
    print("Error in logging out")
